services:
  domserver:
    image: domjudge/domserver:8.2.3
    container_name: domserver
    ports:
      - "80:80"
    environment:
      MYSQL_HOST: ${DB_HOST}
      MYSQL_DATABASE: ${DJ_DB}
      MYSQL_USER: ${DJ_DB_USER}
      MYSQL_PASSWORD: ${DJ_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      CONTAINER_TIMEZONE: Asia/Kolkata
      FPM_MAX_CHILDREN: 40
    restart: always

