services:
  domserver:
    build:
      context: .
      dockerfile: ./redis/Dockerfile
    container_name: domserver
    ports:
      - "80:80"
    environment:
      MYSQL_HOST: ${DB_HOST}
      MYSQL_DATABASE: ${DJ_DB}
      MYSQL_USER: ${DJ_DB_USER}
      MYSQL_PASSWORD: ${DJ_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      CONTAINER_TIMEZONE: Asia/Kolkata
      REDIS_HOST: redis
    restart: always
    volumes:
      - ./redis/php.ini:/usr/local/etc/php/php.ini
      - ./redis/framework.yaml:/opt/domjudge/domserver/webapp/config/packages/framework.yaml
      - ./redis/services.yaml:/opt/domjudge/domserver/webapp/config/services.yaml
    entrypoint: ["bash", "-c"]
    command: 
      - >
        sed --follow-symlinks -i "s/^pm\.max_children = .*$/pm.max_children = ${FPM_MAX_CHILDREN}/" "/etc/php/8.2/fpm/pool.d/domjudge.conf";
        /scripts/start.sh;
    
  

