version: "3.7"

services:
  db:
    image: mariadb:11.2
    environment:
      MYSQL_DATABASE: ${DJ_DB}
      MYSQL_USER: ${DJ_DB_USER}
      MYSQL_PASSWORD: ${DJ_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      CONTAINER_TIMEZONE: Asia/Kolkata
    command: 
      --max-connections=1000 
      --max-allowed-packet=512M
    volumes:
      - db-data:/var/lib/mysql
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
    restart: always
    networks:
      - mariadb-network

volumes:
  db-data:
    name: mariadb-db-data

networks:
  mariadb-network:
    name: mariadb-network