
# Production Docker Compose file for DOMjudge (all services merged)
services:
  traefik:
    container_name: traefik
    image: traefik:${TRAEFIK_VERSION:-v2.9}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-public-certificates:/certificates
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --certificatesresolvers.le.acme.email=${EMAIL}
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --accesslog
      - --log
      - --api
    networks:
      - traefik-public
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.traefik-public-http.rule=Host(`${TRAEFIK_DOMAIN}`)
      - traefik.http.routers.traefik-public-http.entrypoints=http
      - traefik.http.routers.traefik-public-http.middlewares=https-redirect
      - traefik.http.routers.traefik-public-https.rule=Host(`${TRAEFIK_DOMAIN}`)
      - traefik.http.routers.traefik-public-https.entrypoints=https
      - traefik.http.routers.traefik-public-https.middlewares=admin-auth
      - traefik.http.routers.traefik-public-https.tls=true
      - traefik.http.routers.traefik-public-https.service=api@internal
      - traefik.http.routers.traefik-public-https.tls.certresolver=le
      - traefik.http.middlewares.admin-auth.basicauth.users=admin:${TRAEFIK_HASHED_PASSWORD}
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.services.traefik-public.loadbalancer.server.port=80

  db:
    image: mariadb:${MARIADB_VERSION}
    container_name: mariadb
    environment:
      MYSQL_DATABASE: ${DJ_DB}
      MYSQL_USER: ${DJ_DB_USER}
      MYSQL_PASSWORD: ${DJ_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      CONTAINER_TIMEZONE: ${CONTAINER_TIMEZONE}
    command:
      --max-connections=${MARIADB_MAX_CONNECTIONS}
      --max-allowed-packet=${MARIADB_MAX_ALLOWED_PACKET}
      --performance-schema=${MARIADB_PERFORMANCE_SCHEMA}
      --join-buffer-size=${MARIADB_JOIN_BUFFER_SIZE}
      --innodb-buffer-pool-size=${MARIADB_INNODB_BUFFER_POOL_SIZE}
      --innodb-log-file-size=${MARIADB_INNODB_LOG_FILE_SIZE}
      --innodb-log-buffer-size=${MARIADB_INNODB_LOG_BUFFER_SIZE}
      --query-cache-size=${MARIADB_QUERY_CACHE_SIZE}
      --query-cache-type=${MARIADB_QUERY_CACHE_TYPE}
      --tmp-table-size=${MARIADB_TMP_TABLE_SIZE}
      --max-heap-table-size=${MARIADB_MAX_HEAP_TABLE_SIZE}
      --slow-query-log=${MARIADB_SLOW_QUERY_LOG}
      --slow-query-log-file=${MARIADB_SLOW_QUERY_LOG_FILE}
      --long-query-time=${MARIADB_LONG_QUERY_TIME}
    volumes:
      - db-data:/var/lib/mysql
      - ../init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ulimits:
      nofile:
        soft: ${MARIADB_ULIMIT_NOFILE_SOFT}
        hard: ${MARIADB_ULIMIT_NOFILE_HARD}
    restart: always
    networks:
      - mariadb-network

  redis:
    image: redis:${REDIS_VERSION}
    container_name: ${REDIS_CONTAINER_NAME}
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - web-network

  redisinsight:
    image: redislabs/redisinsight:${REDIS_INSIGHT_VERSION}
    container_name: ${REDIS_INSIGHT_CONTAINER_NAME}
    restart: always
    ports:
      - 5540:5540
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    networks:
      - web-network

  domserver:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: always
    privileged: true
    hostname: domserver
    container_name: domserver
    volumes:
      - submissions-data:/opt/domjudge/domserver/submissions/
      - judgings-data:/opt/domjudge/domserver/judgings/
      - ../redis/php.ini:/usr/local/etc/php/php.ini
      - ../redis/framework.yaml:/opt/domjudge/domserver/webapp/config/packages/framework.yaml
      - ../redis/services.yaml:/opt/domjudge/domserver/webapp/config/services.yaml
      - ../services/template-overrides/base.html.twig:/opt/domjudge/domserver/webapp/templates/team/base.html.twig
      - ../services/template-overrides/submit_scripts.html.twig:/opt/domjudge/domserver/webapp/templates/team/partials/submit_scripts.html.twig
    environment:
      MYSQL_HOST: ${DJ_DB_HOST}
      MYSQL_DATABASE: ${DJ_DB}
      MYSQL_USER: ${DJ_DB_USER}
      MYSQL_PASSWORD: ${DJ_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      CONTAINER_TIMEZONE: ${CONTAINER_TIMEZONE}
      FPM_MAX_CHILDREN: ${FPM_MAX_CHILDREN}
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.middlewares.prod-redirect.redirectscheme.scheme=https
      - traefik.http.routers.domserver-http.rule=Host(`${SITES}`)
      - traefik.http.routers.domserver-http.entrypoints=http
      - traefik.http.routers.domserver-http.middlewares=prod-redirect
      - traefik.http.routers.domserver-https.rule=Host(`${SITES}`)
      - traefik.http.routers.domserver-https.entrypoints=https
      - traefik.http.routers.domserver-https.tls=true
      - traefik.http.routers.domserver-https.tls.certresolver=le
      - traefik.http.services.domserver.loadbalancer.server.port=80
    networks:
      - traefik-public
      - mariadb-network
      - web-network
    depends_on:
      - db

  domserver-judge-1:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: always
    privileged: true
    hostname: domserver-judge
    volumes:
      - submissions-data:/opt/domjudge/domserver/submissions/
      - judgings-data:/opt/domjudge/domserver/judgings/
    environment:
      MYSQL_HOST: ${DJ_DB_HOST}
      MYSQL_DATABASE: ${DJ_DB}
      MYSQL_USER: ${DJ_DB_USER}
      MYSQL_PASSWORD: ${DJ_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      CONTAINER_TIMEZONE: ${CONTAINER_TIMEZONE}
    labels:
      - traefik.enable=false
    networks:
      - mariadb-network
      - web-network
      - judge-network

  judgehost-1:
    image: domjudge/judgehost:${JUDGEHOST_VERSION}
    restart: always
    privileged: true
    hostname: ${JUDGEHOST_HOSTNAME_1}
    container_name: ${JUDGEHOST_CONTAINER_NAME_1}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    environment:
      DAEMON_ID: "${JUDGEHOST_DAEMON_ID_1}"
      DOMSERVER_BASEURL: http://${DOMSERVER_MAIN_IP}/
      JUDGEDAEMON_PASSWORD: ${JUDGEHOST_PASSWORD}
      CONTAINER_TIMEZONE: ${CONTAINER_TIMEZONE}
    networks:
      - mariadb-network
      - web-network

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.23.0
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`${PORTAINER_DOMAIN}`)"
      - "traefik.http.routers.portainer.entrypoints=http,https"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=le"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.portainer-http.middlewares=portainer-https-redirect"

# Volumes
volumes:
  traefik-public-certificates:
  db-data:
    name: mariadb-db-data
  redis-data:
  submissions-data:
    name: domserver-submissions-data
  judgings-data:
    name: domserver-judgings-data
  portainer-data:

# Networks
networks:
  traefik-public:
    name: traefik-public
  mariadb-network:
    name: mariadb-network
  web-network:
    name: web-network
  judge-network:
    name: judge-network
