services:
  judgehost-1:
    image: domjudge/judgehost:${JUDGEHOST_VERSION}
    restart: always
    privileged: true
    hostname: ${JUDGEHOST_HOSTNAME_1}
    container_name: ${JUDGEHOST_CONTAINER_NAME_1}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup      
    environment:      
      DAEMON_ID: "${JUDGEHOST_DAEMON_ID_1}"
      DOMSERVER_BASEURL: http://${DOMSERVER_MAIN_IP}/
      JUDGEDAEMON_PASSWORD: ${JUDGEHOST_PASSWORD}
      CONTAINER_TIMEZONE: ${CONTAINER_TIMEZONE}
    networks:
      - mariadb-network
      - web-network
      
networks:
  mariadb-network:
    name: mariadb-network
    external: true
  web-network:
    name: web-network
    external: true
