services:
  db:
    image: mariadb:${MARIADB_VERSION}
    container_name: mariadb
    environment:
      MYSQL_DATABASE: ${DJ_DB}
      MYSQL_USER: ${DJ_DB_USER}
      MYSQL_PASSWORD: ${DJ_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      CONTAINER_TIMEZONE: ${CONTAINER_TIMEZONE}
    command: 
      --max-connections=${MARIADB_MAX_CONNECTIONS}
      --max-allowed-packet=${MARIADB_MAX_ALLOWED_PACKET}
      --performance-schema=${MARIADB_PERFORMANCE_SCHEMA}
      --join-buffer-size=${MARIADB_JOIN_BUFFER_SIZE}
      --innodb-buffer-pool-size=${MARIADB_INNODB_BUFFER_POOL_SIZE}
      --innodb-log-file-size=${MARIADB_INNODB_LOG_FILE_SIZE}
      --innodb-log-buffer-size=${MARIADB_INNODB_LOG_BUFFER_SIZE}
      --query-cache-size=${MARIADB_QUERY_CACHE_SIZE}
      --query-cache-type=${MARIADB_QUERY_CACHE_TYPE}
      --tmp-table-size=${MARIADB_TMP_TABLE_SIZE}
      --max-heap-table-size=${MARIADB_MAX_HEAP_TABLE_SIZE}
      --slow-query-log=${MARIADB_SLOW_QUERY_LOG}
      --slow-query-log-file=${MARIADB_SLOW_QUERY_LOG_FILE}
      --long-query-time=${MARIADB_LONG_QUERY_TIME}
    volumes:
      - db-data:/var/lib/mysql
    ulimits:
      nofile:
        soft: ${MARIADB_ULIMIT_NOFILE_SOFT}
        hard: ${MARIADB_ULIMIT_NOFILE_HARD}
    restart: always
    networks:
      - mariadb-network


volumes:
  db-data:
    name: mariadb-db-data


networks:
  mariadb-network:
    name: mariadb-network